### ISSUE TITLE
ics does not support 5545 3.1 (long line folding)

### ISSUE THREAD

**Issue by acanewby** [ics-py/ics-py#215]
First off, loving the library!  Thanks for all the hard work.

I've implemented an ics file generator and noticed that some of my `LOCATION:` values are flagged by the icalendar.org validator.

Turns out that [RFC 5545 3.1. Content Lines](http://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html) is not being respected by `ics.py`.

ics.py: 0.6
python 3.74
macOs Catalina (10.15.2)

Basically, for values exceeding 75 characters, you need to "fold" by inserting a CR [SPACE] sequence after each 75 characters.

Looking at the `ics.py` code, it would seem that perhaps a good place to do this would be:

* `fold` at the end of `ics.utils.escape_string()`, just before the string is returned
* `unfold` at the beginning of `ics.utils.unescape_string()`, just before the string is unescaped

I'm very new to this library, so not (yet) ready to dive into the code.  However, if you agree that the above is the right approach, I'd be happy to try and knock out a fix and submit a PR.

**Comment by acanewby** [comment]
OK - after a little more research, I see how you are supporting UNfolding in `grammar/parse.py`.  So, it looks as if we can import folded calendar lines and parse them.  

Presumably, then, part of the approach would be to implement the orthogonal `fold_lines()` function in `grammar/parse.py` and then what?  Modify `Container:__str__()`?

**Comment by C4ptainCrunch** [comment]
Indeed, we do support unfolding but not yet folding.

> Presumably, then, part of the approach would be to implement the orthogonal fold_lines() function in grammar/parse.py and then what? Modify Container:__str__()?

It seems like a good approach :)

**Comment by N-Coder** [comment]
Small note: We need to be extra careful with unicode data in the lines being folded, so that we don't wrap a two byte value in the middle (like [here](https://bugzilla.redhat.com/show_bug.cgi?id=1646393#c12)) or split a [compound emoji](https://blog.emojipedia.org/unicode-behind-the-curtain/), e.g. with a Zero Width Joiner in the middle.
