### ISSUE TITLE
Serialize events in chronological order

### ISSUE THREAD

**Issue by leingang** [ics-py/ics-py#251]
I just downloaded this library and it seems to be just what I need.  Thanks!

I want to set up regression tests of code that generate ICS files.  But successive runs aren't serializing the events in the same order, so my tests are failing.  I guess this is because a calendar's `events` property is a set and not a list.  

The only way I know to serialize a calendar is to call `str` on it.  Is there a way which makes sure its events are given a specific order (e.g., chronological by starting time)?

I'm using ics 0.7 and python 3.6.

**Edit** This might be a good feature, but not for this use case, I just realized.  The code may produce the same set of events, but they won't have the same UID's, ever.  So the serializations won't be equal no matter what order the events go in.

**Comment by N-Coder** [comment]
This is already fixed in the v0.8 development branch, where [`Calendar.events`](https://github.com/C4ptainCrunch/ics.py/blob/3b544fba4b46430fc624e425bf6ddc9ea1cd9406/src/ics/icalendar.py#L21) is a `List` that preservers the order from the parsed file and any following insertions. Unfortunately, we can't easily backport that to v0.7 without breaking stuff. But maybe I can prepare an "alpha" kind of release of v0.8 sometime soon.

The issue with the changing UIDs is known and documented [here](https://github.com/C4ptainCrunch/ics.py/blob/timezones/doc/event-cmp.rst#equality) for v0.8. It just occurred to me that being able to turn this off and thus getting deterministic event instances might be a useful feature, if reproduceability is more important to your use-case than uniqueness.

**Comment by N-Coder** [comment]
Commit 27279885334eebd337be620e0c247c059d6a4e87 adds a context manager and decorator that ensures that the UIDs and dtstamp values of all the events you create are deterministic. Example usage of these deterministic values together with event sorting can be seen in the corresponding [test file](https://github.com/ics-py/ics-py/pull/294/commits/27279885334eebd337be620e0c247c059d6a4e87#diff-adb0aae4fa644dd7f54c4626aedd98415d1529670dd9df14300cd22bf8b0bcad):
```python
from datetime import datetime

from ics import *
from ics.event import deterministic_event_data
from ics.timezone import UTC

cal = Calendar()
with deterministic_event_data(uid="my-uid@example.com", dtstamp=datetime(1970, 1, 1, 0, 0, tzinfo=UTC)):
    # uid and dtstamp parameters can also be left out

    cal.events.append(Event("second", datetime(2000, 2, 1, 12, 0)))
    cal.events.append(Event("fourth", datetime(2000, 4, 1, 12, 0)))
    cal.events.append(Event("third", datetime(2000, 3, 1, 12, 0)))
    cal.events.append(Event("first", datetime(2000, 1, 1, 12, 0)))

    assert cal.events[0] == Event("second", datetime(2000, 2, 1, 12, 0)) # will have the same uid

assert cal.events[0] != Event("second", datetime(2000, 2, 1, 12, 0)) # will have a different uid again

assert [e.summary for e in cal.events] == ["second", "fourth", "third", "first"] # insertion order

cal.events = sorted(cal.events)
assert [e.summary for e in cal.events] == ["first", "second", "third", "fourth"] # by default, we sort by start time
print(cal.serialize())
assert cal.serialize() == """
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py - http://git.io/lLljaA
BEGIN:VEVENT
DTSTART:20000101T120000
SUMMARY:first
UID:my-uid@example.com
DTSTAMP:19700101T000000Z
END:VEVENT
BEGIN:VEVENT
DTSTART:20000201T120000
SUMMARY:second
UID:my-uid@example.com
DTSTAMP:19700101T000000Z
END:VEVENT
BEGIN:VEVENT
DTSTART:20000301T120000
SUMMARY:third
UID:my-uid@example.com
DTSTAMP:19700101T000000Z
END:VEVENT
BEGIN:VEVENT
DTSTART:20000401T120000
SUMMARY:fourth
UID:my-uid@example.com
DTSTAMP:19700101T000000Z
END:VEVENT
END:VCALENDAR
""".strip().replace("\n", "\r\n")

cal.events = sorted(cal.events, key=lambda e: e.summary) # but we can also sort by other keys
assert [e.summary for e in cal.events] == ["first", "fourth", "second", "third"]

```

**Comment by alex-ball** [comment]
For anyone else using v0.7 and impatient for this feature, here is a workaround.

Create your own serializer:

```python
class AscendingCalendarSerializer(CalendarSerializer):
    def serialize_event(calendar, container):
        ordered_events = list(calendar.events)
        ordered_events.sort()
        for event in ordered_events:
            container.append(event.serialize())

    def serialize_todo(calendar, container):
        ordered_todos = list(calendar.todos)
        ordered_todos.sort()
        for todo in ordered_todos:
            container.append(todo.serialize())
```

Use it like this:

```python
c = Calendar()
c.Meta.serializer = AscendingCalendarSerializer
```
