### ISSUE TITLE
unsupported TZID parm: X-RICAL-TZSOURCE=TZINFO

### ISSUE THREAD

**Issue by jrsenthilk** [ics-py/ics-py#268]
Hi, 

I tried reading an ics file from an URL and below are part of the ICS file:
URL : https://ottawaphysioclinic.janeapp.com/ical/80py0rjC7SeLVVoXNzn6/appointments.ics

```
BEGIN:VCALENDAR
PRODID;X-RICAL-TZSOURCE=TZINFO:-//com.denhaven2/NONSGML ri_cal gem//EN
CALSCALE:GREGORIAN
VERSION:2.0
X-WR-CALNAME::Apollo Physical Therapy Centres Appointments
BEGIN:VTIMEZONE
TZID;X-RICAL-TZSOURCE=TZINFO:America/Toronto
BEGIN:STANDARD
DTSTART:20201101T020000
RDATE:20201101T020000
RDATE:20211107T020000
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
TZNAME:EST
END:STANDARD
BEGIN:DAYLIGHT
```

But, I keep getting this error: `unsupported TZID parm: X-RICAL-TZSOURCE=TZINFO`

My code is just a one liner : `c = Calendar(requests.get(subscribe_url).text)`

May I know what is causing this issue? The file format seems to be correct as I have tried validating it.

Any help is highly appreciated. Thanks

**Comment by N-Coder** [comment]
This error comes from the `dateutil` library, which we use for parsing vTimezones. This library only knows the few required standard properties and throws this exception when it doesn't know a property/attribute/parameter - unlike ics.py, which simply stores all of them in the `extras` container. The next version will have a fix for this, as we'll do all that parsing ourselves there. Until then, the easiest fix would be removing the vTimezone declaration from the calendar, by first translating the string to a list of containers using `calendar_string_to_containers`, removing the entry with name `VTIMEZONE` and only then passing the modified container to the constructor of `Calendar` (see its [`__init__` method](https://github.com/ics-py/ics-py/blob/version-0.7/ics/icalendar.py#L63)), which will make ics.py fall back to your system timezones for all datetimes that use timezone `America/Toronto`.

**Comment by N-Coder** [comment]
The exception should no longer be there with the current `master` branch, #293 adds a few further fixes revolving around your example including a specific [test case](https://github.com/ics-py/ics-py/pull/293/files#diff-1c598bfe6c3ea1bd92208fd85ba96df44c669cf00f9f56ac2f068fae81ca44dd) for this. Could you check whether everything works with the code from that branch?

**Comment by haggaret** [comment]
Any chance this fix is going to be available in a new version on pypi?

**Comment by N-Coder** [comment]
See [here](https://github.com/ics-py/ics-py/issues/245#issuecomment-923798362), this unfortunately is no simple "fix" but pretty much an entire rewrite. If you really want to have this before even the alpha version is ready, I'd recommend installing [directly from git](https://pip.pypa.io/en/stable/topics/vcs-support/) and providing feedback in the linked issue. :wink:
