### ISSUE TITLE
create sdist for pypi

### ISSUE THREAD

**Issue by dlangille** [ics-py/ics-py#283]
At https://pypi.org/project/ics/#files there is no sdist, as is standard pypi/python practice.

Any plans to create one? It would greatly simplify the work of your downstream packagers.

Thank you.

**Comment by N-Coder** [comment]
Version 0.8 (whenever that will be ready) uses poetry as new tool for building and publishing. It seems like poetry also automatically publishes a source distribution, at least that's the case for my test uploads here (don't mind the version number):
https://test.pypi.org/project/ics/#files
I also tried to manually generate a sdist for v0.7, if this looks good I can also push it to the production repo.
https://test.pypi.org/project/ics/0.7/#files

**Comment by koobs** [comment]
@N-Coder I imagine #274 covers this?

**Comment by N-Coder** [comment]
That PR will call `poetry publish -r pypi` automatically for new releases starting with 0.8. First part of my comment was to check whether that actually yields the right artifacts ([does it?](https://test.pypi.org/project/ics/#files)), second part was to find a solution for the already published 0.7, as that isn't using poetry and backporting all the build system changes the PR relies on would be a lot of work with little use. Plus I don't know whether there will be a 0.7.1 release before 0.8.

**Comment by koobs** [comment]
That's ok we can grab from tagged GitHub sources in the meantime Unless you wouldn't mind running setup.py sdist for 0.7.0

**Comment by N-Coder** [comment]
> Unless you wouldn't mind running setup.py sdist for 0.7.0

I did that here:
https://test.pypi.org/project/ics/0.7/#files
If that looks alright I can push it to production.

**Comment by dlangille** [comment]
We're about to build a FreeBSD package from this. We will provide feedback. Thank you.

**Comment by dlangille** [comment]
> We're about to build a FreeBSD package from this. We will provide feedback. Thank you.

Success here. Thank you.

**Comment by N-Coder** [comment]
I also pushed it to production
