### ISSUE TITLE
CALSCALE added after parsing

### ISSUE THREAD

**Issue by Skillkiller** [ics-py/ics-py#302]
When you create a new empty calendar it looks like this:
```plain
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py - http://git.io/lLljaA
END:VCALENDAR
```

If you now read this empty calendar back in and have it rewritten to a file unchanged, there is a difference. The line has been added: ``CALSCALE:GEORGIAN``.
End file:
```plain
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py - http://git.io/lLljaA
CALSCALE:GEORGIAN
END:VCALENDAR
```

This behavior can also be observed when events are added to the first calendar at runtime.
Minimal Code used to show the behavior:
```python
from ics import Calendar
c = Calendar()
with open("test.ics", 'w') as file:
    file.writelines(c)
with open("test.ics", "r") as file1:
    l = file1.read()

c = Calendar(l)
with open("test2.ics", 'w') as file:
    file.writelines(c)
```

**Comment by N-Coder** [comment]
This no longer happens with version 0.8:
```
>>> from ics import Calendar
>>> c = Calendar()
>>> c.serialize()
'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:ics.py - http://git.io/lLljaA\r\nEND:VCALENDAR'
>>> Calendar(c.serialize()).serialize()
'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:ics.py - http://git.io/lLljaA\r\nEND:VCALENDAR'
```
But this reminds me that we might want to include the version of ics.py in the PRODID field. :grin:
