### ISSUE TITLE
str(Calendar('string')) return not a string

### ISSUE THREAD

**Issue by begem** [ics-py/ics-py#305]
have next code
```
f=open(file,'r+')
cal=Calendar('normal calendar')
f.write(cal) #write normal calendar whith spaces

cal=Calendar('data from ics module') #mean open file was saved from ics
f.write(cal) #return binary data
#but
print(cal)#return normal data
#but
print(cal,file=f) #write binary data
```
also it is very strong err: cant handle it

**Comment by N-Coder** [comment]
Sorry, I'm absolutely unable to understand what you are trying to tell me. What is the exception you are talking about? Please provide a minimal calendar data input to reproduce your issue. Which version of ics.py are your using?

**Comment by begem** [comment]
Sorry... There was my mistake... I was use file.truncate(0) before file.write(str(ics.Calendar())) and had wrong results irregulary (some time it was normal text, some time it was binary as text )...
