### ISSUE TITLE
Events mixed when writing to file again

### ISSUE THREAD

**Issue by Skillkiller** [ics-py/ics-py#306]
Hello,
I have several large calendars. When I read these calendars and write them back to a file without any further changes, some calendar entries are changed in their order. Is there a way to ensure that the entries are always serialized in the same order and is this a desired behavior?

For demonstration purposes I provide here a calendar where this is the case. Due to the size unfortunately as Gist because a direct embedding is not possible: https://gist.github.com/Skillkiller/aa602e4269ffb44c19023742c224eea8

I have had the calendar read in and rewritten several times, here is the history of it: https://gist.github.com/Skillkiller/1cc06322613d36d3fe271078597517bd/revisions

```
from ics import Calendar
with open("working/test1.ics", "r") as file1:
    l = file1.read()
c = Calendar(l)
with open("working/test1.ics", 'w') as file:
    file.writelines(c)```

**Comment by Skillkiller** [comment]
Further note: An ics file often results in the same intermixed output file.
So if I always read in file "1.ics" and save in "2.ics", "2.ics" is often the same intermixed.

**Comment by N-Coder** [comment]
This is a known issue of v0.7 due to events being stored in a `set` instead of a `list` with deterministic ordering.
Version 0.8 fixed this, you can try installing it by using `pip install git+https://github.com/ics-py/ics-py.git`.
In general, I wrote more test for deterministic behaviour for this version, so maybe trying the switch should also fix problems like the one in your other issue.
Unfortunately, there are also some other huge changes in that version, so it might still take some time until an official release, but the current `main` branch should be mostly stable and usable.

**Comment by Skillkiller** [comment]
Yes exactly such a technical background I had expected. The version 0.8 solves exactly my problem. After an update I have unfortunately the problem that I wide extra ContentLines are serialized more. This is definitely due to my usage. Can you give me a minimal example where I create a new calendar which has an extra content line?
The example as it can be found in the documentation for 0.7 does not seem to work anymore.

**Comment by N-Coder** [comment]
`Event.extra` needs to be a `Container` (which is `list` with an added name attribute) with the right name set, as that will be used for the `BEGIN:XYZ` of the event in the serialised ics. So assigning it to a list won't work, but modifying the Container inplace (e.g. `clear`, `append` or `event.extra[:] = [ContentLine(...), ...]` for replacing the contents) should be fine. If that doesn't work, could you post what goes wrong? I unfortunately don't have a machine at hand to confirm this myself.

**Comment by Skillkiller** [comment]
Yes you are absolutely right. That was my mistake again. In one project I read in an already existing file and therefore didn't set the extras and in my other test I didn't scroll to the bottom because I expected the extra at the top.
