### ISSUE TITLE
ORGANIZER not parsed correctly

### ISSUE THREAD

**Issue by xKippi** [ics-py/ics-py#320]
I have a calendar with an ORGANIZER line like this:
`ORGANIZER;CN="XXX:online Example Organization":MAILTO:noreply@example.org `.

When this gets parsed however, the quotation marks get removed and mailto gets converted to lower case, yielding:
`ORGANIZER;CN=XXX:online Example Organization:mailto:noreply@example.org`

This presents a problem because if you save it like this and then parse it again, the result is this:
`CN=XXX:mailto:online Example Organization:mailto:noreply@example.org`

Also, I dislike that the "mailto" gets converted to lower case, but that's not that much of a problem.

Environment:
 - Arch Linux
 - Python v3.10.2
 - ics v0.7 (From the [AUR](https://aur.archlinux.org/packages/python-ics))

I've attached a script reproducing the problem for reference: [bug.py](https://github.com/ics-py/ics-py/files/8206922/bug.py.txt)

**Comment by N-Coder** [comment]
Could you try again with the latest version from the master branch? You can install it with
```bash
pip install git+https://github.com/ics-py/ics-py.git
```

**Comment by N-Coder** [comment]
The "mailto" being converted to lowercase probably comes from using python's built-in [`urlparse`](https://docs.python.org/3/library/urllib.parse.html) to represent the URLs. One could probably use one of many other libraries ([rfc3986](https://rfc3986.readthedocs.io/en/latest/), [rfc3987](https://pypi.org/project/rfc3987/), [hyperlink](https://hyperlink.readthedocs.io/en/latest/index.html), [furl](https://github.com/gruns/furl), ...) as a replacement that might allow customizing this, but I haven't looked into that. The biggest issue there is probably deciding which one to use / how to support multiple of these libraries.

**Comment by xKippi** [comment]
I've tried now, seems to work with the latest version from the master branch. so I guess this is obsolete now. However, are you going to fix this in v0.7 or will it only be fixed when v0.8 comes out?

Regarding the lowercase conversion of "mailto", would be nice if you could look at that if you get to. But as I said, this is a rather minor problem.

**Comment by N-Coder** [comment]
The "fix" probably comes from the entire parsing/serialisation system being rewritten, so a backport would be pretty much the same as a new release and that might still take some time, unfortunately.
More URL libs won't make it into that release, but I can open up an issue to at least track this.
