### ISSUE TITLE
Quotes in TZID seem to break validation and at least outlook365 imports

### ISSUE THREAD

**Issue by rkdarst** [ics-py/ics-py#324]
I'm no export in ICS, but I am posting here in case it helps someone / it is actually an issue.  This is done with the latest development version of ics-py:

I had a calendar object with timezones that were explicit UTC offsets (e.g. timezone UTC+03:00).  When running through [the validator](https://icalendar.org/validator.html?url=https://users.aalto.fi/~darstr1/hidden/team-quoted-tzid.ics) I saw this error:

```
Invalid TZID value or missing VTIMEZONE component ("UTC+03:00") near line # 167Reference: 3.2.19. Time Zone Identifier
```
The line in question (it clearly needs quotes because it has a `:` in there):
```
DTSTART;TZID="UTC+03:00":20220519T110000
```

The TZID block is defined as (with no quotes):
```
TZID:UTC+03:00
```

After some debugging, I saw the problem was the quotes themselves.  One may think that adding quotes to the TZID definition would work, but it didn't.  Only removing quotes (and thus the `:`) from all TZIDs seemed to make everything work.  In the end, we stopped using offsets and and used symbolic timezones that ics-py generates without quotes (`DTSTART;TZID=/ics.py/2020.1/Europe/Stockholm:20220228T140000`).

The current form does import into Google Calendar and Thunderbird successfully. But it silently failed with Microsoft Outlook 365 (the cloud version), which unfortunately some of us have to use.  So this remained for quite a while before we dug deep enough to find it.

I don't know the right solution, but my attempt would be "rephrase the timezone offsets so that it doesn't need quotes".

Thanks for ics-py!  I use it in this project: https://github.com/coderefinery/git-calendar (via https://github.com/scientific-python/yaml2ics)

**Comment by strobeflash** [comment]
@rkdarst I took a quick look at this without any indepth knowledge of the codebase to make it reproducible. I believe Microsoft Outlook 365 is the business/school version of the product for which I don't have an easily accessible account so I tested on outlook.live.com, hoping the handling is comparable.

My observations: Both the original ics file and the one with the manual fix could not be imported into my outlook.live.com calendar. These are the files I used.

[orig.ics](https://users.aalto.fi/~darstr1/hidden/team-quoted-tzid.ics)
[fixed.ics](https://pastebin.com/Lw3msicb)

```
$ diff team-quoted-tzid.ics fixed.ics 
168,169c168,169
< DTSTART;TZID="UTC+03:00":20220519T110000
< DTEND;TZID="UTC+03:00":20220520T140000
---
> DTSTART;TZID=/ics.py/2020.1/Europe/Stockholm:20220228T140000
> DTEND;TZID=/ics.py/2020.1/Europe/Stockholm:20220228T140000
179c179
< END:VCALENDAR
\ No newline at end of file
---
> END:VCALENDAR
```
What did work is importing fixed.ics into Mozilla Thunderbird, making a minimal change do save it and then importing that newly modified ics into the outlook.live.com calendar. Diffing the file did not reveal any significant differences to me at a quick glance, would need to check this further. This approach did NOT work with orig.ics.

[thunderbird.ics](https://pastebin.com/0hcEC1Yr)

Also, after reviewing valid syntax according to the RFC I think that double-quotes (") are essentially a valid character. Not saying that theres no room for improvement, but that it seems compliant to the standard.

[3.2.19.  Time Zone Identifier](https://datatracker.ietf.org/doc/html/rfc5545#section-3.2.19)

```   Format Definition:  This property parameter is defined by the
      following notation:

       tzidparam  = "TZID" "=" [tzidprefix] paramtext

       tzidprefix = "/"
```

[3.1.  Content Lines](https://datatracker.ietf.org/doc/html/rfc5545#section-3.1)
```

     SAFE-CHAR     = WSP / %x21 / %x23-2B / %x2D-39 / %x3C-7E
                   / NON-US-ASCII
     ; Any character except CONTROL, DQUOTE, ";", ":", ","

...

     paramtext     = *SAFE-CHAR
```

Is the diff correct?
Does my summary match your observation?
How did you generate the calendar object?

**Comment by C4ptainCrunch** [comment]
Hi 👋 
This issue seems stale as nothing moved since a long time. I'm closing it now but feel free to reopen if needed :)
