### ISSUE TITLE
Release of 0.7.1

### ISSUE THREAD

**Issue by C4ptainCrunch** [ics-py/ics-py#345]
Now that #318 has been merged, i fixed the tests and the branch is green. I think we can start the process of releasing version 0.7.1. This issue will be used to track it.

Todo:
- [x] Write some release notes
- [x]  Copy the releases notes into `main`
- [x] Setup a environment with Python 3.6 to build the package
- [x] Find the old build process and verify it still works
- [x] Build and test the build
- [x] Upload to Pypi

**Comment by C4ptainCrunch** [comment]
I uploaded a build of 0.7.1 on [**test** pypi](https://test.pypi.org/project/ics/0.7.1/#description). Could somebody check that the files look correct ?

https://test.pypi.org/project/ics/0.7.1/#files

```
pip install -i https://test.pypi.org/simple/ ics==0.7.1
```

**Comment by C4ptainCrunch** [comment]
Great thanks :) Here are the notes in the changelog: https://github.com/ics-py/ics-py/blob/version-0.7/CHANGELOG.rst#071
@N-Coder : could you confirm we are ok and i should release 0.7.1 to the *prod* pypi ?

**Comment by N-Coder** [comment]
Except for the two typos in "deprecation" everything looks good to me :wink:

**Comment by C4ptainCrunch** [comment]
It's done ! https://pypi.org/project/ics/0.7.1/

**Comment by C4ptainCrunch** [comment]
Of course, something had to fail, the doc is not building. I'm trying the same fix as on `main`: upgrading to Sphinx 5
