### ISSUE TITLE
event._end_time check in serialize_all_day of EventSerializer

### ISSUE THREAD

**Issue by nathgrin** [ics-py/ics-py#359]
def serialize_all_day(event, container):
        if event.begin and event.all_day:
            ...
            if event._end_time:
               ...

but ._end_time is not set because its an all_day event
changing to if event.end worked for me
edit: nvm it didnt work, related to off-by-one issues for all_day events iguess

**Comment by N-Coder** [comment]
The serialization code of v0.8 that is currently on `main` looks vastly different, so this is probably fixed. I'm still linking #92, #155, #173 for reference as they relate to the off-by-one errors (which we need to have proper tests for in 0.8) and closing this.

**Comment by nathgrin** [comment]
thanks!
