### ISSUE TITLE
0.7.2 shows unnecessary deprecation warnings

### ISSUE THREAD

**Issue by jakub-bacic** [ics-py/ics-py#360]
The following example shows deprecation warning:
```
FutureWarning: Behaviour of str(Component) will change in version 0.9 to only return a short description, NOT the ics representation. Use the explicit Component.serialize() to get the ics representation.
```
even though, it doesn't explicitly use `str` on any Component object:
```python
import datetime

from ics import Calendar, DisplayAlarm, Event

cal = Calendar()
event = Event(alarms=[DisplayAlarm(trigger=datetime.datetime.now())])
cal.events.add(event)

# that line will show deprecation warning
cal.serialize()
```

**Comment by N-Coder** [comment]
There's always that one place you miss... :see_no_evil: Thanks for fixing this! Its probably best to wait a little longer and see whether any further things come up and only then do a further release. Until then you can easily either suppress the warning or install 0.7 from the respective branch.

**Comment by adam-conway** [comment]
Hey @N-Coder, can we release a patch version with this change now? We've still got these warnings in production and would love to get rid of them!
