### ISSUE TITLE
`.summary` does not set the event name

### ISSUE THREAD

**Issue by AirbandAF** [ics-py/ics-py#362]
Hi,

I've just installed this package and I have run into a couple of issues. I am on version 0.7.2 and using Python 3.10.5 on a Mac (OSX 12.1)
I used the code given in the example to create an event:
```
c = Calendar()
e = Event()
e.summary = "My cool event"
e.description = "A meaningful description"
e.begin = dt.datetime.fromisoformat("2022-06-06T12:05:23+02:00")
e.end = dt.datetime.fromisoformat("2022-06-06T13:05:23+02:00")
c.events.append(e)
c
```
However, on running this I get the following error:
`AttributeError: 'set' object has no attribute 'append'`

This can be fixed by replacing with events.add instead of .append.

However, inspite of this, the resulting ics does not contain an event name. This is true both when printing the object and writing to the file.

The resulting object is this:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py - http://git.io/lLljaA
BEGIN:VEVENT
DESCRIPTION:A meaningful description
DTEND:20220606T110523Z
DTSTART:20220606T100523Z
UID:11c1c292-de41-4fa7-915a-48aaf85d09d8@11c1.org
END:VEVENT
END:VCALENDAR
```

I'm not sure if I'm doing something wrong or there is an issue with the code.

**Comment by C4ptainCrunch** [comment]
Hi,

Indeed, you should use `.add` and not `.append`, it seems you are using an old introduction snippet (the doc seems up to date https://icspy.readthedocs.io/en/stable/#create-a-new-calendar-and-add-events)

For the missing name part : to set an event name, you should use `e.name = 'xxx'` not `e.summary`. We made the choice to use the more common "name" property and not "summary" that requires you to know the terminology of the RFC5545.

Does this solve your problem ?

**Comment by C4ptainCrunch** [comment]
@LemuelKL Oh, nice catch. This is a side effect of me trying to release a pre-release this morning, indeed, readthedocs should point to `stable` instead. I'll try to fix that.

**Comment by AirbandAF** [comment]
Hi, 
Thanks very much for your help! This makes sense now.
I also went through pypi and that is how I found the docs, I thought I was going crazy as I was following the docs exactly but it wasn't working.
