### ISSUE TITLE
ValueError: A VALARM must have at least one DESCRIPTION

### ISSUE THREAD

**Issue by rscmbbng** [ics-py/ics-py#363]
Parsing a Nextcloud calendar throws the error in the Issue title. Because multiple Nextcloud versions are affected (https://github.com/nextcloud/calendar/issues/4490), I am also opening an issue here to track it.

ics-py version:  `0.7.1`

**Comment by allenporter** [comment]
From the RFC https://www.rfc-editor.org/rfc/rfc5545#section-3.6.6
```
dispprop   = *(
                  ;
                  ; The following are REQUIRED,
                  ; but MUST NOT occur more than once.
                  ;
                  action / description / trigger /
                  ;
                  ; 'duration' and 'repeat' are both OPTIONAL,
                  ; and MUST NOT occur more than once each;
                  ; but if one occurs, so MUST the other.
                  ;
                  duration / repeat /
                  ;
                  ; The following is OPTIONAL,
                  ; and MAY occur more than once.
                  ;
                  x-prop / iana-prop
```

This is a required field for a display property like a reminder. I think you were correct to file this bug on next cloud if it is not making valid exports.

**Comment by C4ptainCrunch** [comment]
It seems like nextcloud is fixing it on their side, i'm closing it here :)
