### ISSUE TITLE
Alarm not showing up in Calendar

### ISSUE THREAD

**Issue by lSh4dowl** [ics-py/ics-py#367]
When I add a Alarm with the following line:
`e.alarms.append(DisplayAlarm(trigger=timedelta(hours=-2)))`
it will add it in this form in the file:
```BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:
TRIGGER:-PT2H
END:VALARM
```

But in gmail or Apple Mail, the alarm will not be set.

**Comment by N-Coder** [comment]
You could try the validator [here](https://icalendar.org/validator.html) to see whether its a problem with the respective frontend or on our side

**Comment by lSh4dowl** [comment]
This site does not show any errors when running the files, but Google Calendar as well as MacOS Calendar do not recognize the alarms.

**Comment by N-Coder** [comment]
Then it's probably a problem with the frontends not being standards-compliant, not ics.py. You can try creating an alarm with one of those tools, exporting the calendar and loading it with ics.py so see how these tools would like to have their alarms. Then try to reproduce that with your code. ;)
