### ISSUE TITLE
Add support for repeating events

### ISSUE THREAD

**Issue by K3vX21** [ics-py/ics-py#376]
Like the feature available in Google Calendar, where events can repeat at regular intervals based on days, weeks, months, etc.

**Comment by strobeflash** [comment]
@K3vX21 i'm assuming you found how to perform this, was it hard to find? if so, where would have you expected the docs and where did you find finally?

**Comment by K3vX21** [comment]
Although I originally closed this issue because it was redundant with a previous issue (#14), I was able to find a workaround using the [.extra attribute](https://icspy.readthedocs.io/en/stable/advanced.html) to manually implement the [Recurrence Rule](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html). As I've mentioned in #377, you'll most likely need to add `from ics.grammar.parse import ContentLine` (something that took me a sec to find) if you're using Python to do this. Let me know if you have any other questions!

**Comment by K3vX21** [comment]
I used this in my most [recent webscraping project](https://github.com/K3vX21/atlas-to-ics/). The following snippet from that might be helpful in showing what I mean:
```
from ics.grammar.parse import ContentLine
# some irrelevant code
e = Event()
# some more irrelevant code
e.extra.append(ContentLine(
            name="RRULE", value=f"FREQ=WEEKLY;COUNT={15*len(course.days)};WKST=SU;BYDAY={days_csv}"))
```
