### ISSUE TITLE
Error while setting up extra for Event class

### ISSUE THREAD

**Issue by 2rueSid** [ics-py/ics-py#385]
Hello!

I'm trying to add `SEQUENCE` field.
```python
    # setting up event
    event = Event(
        name=calendar_event_data.event_name,
        begin=start_dt,
        end=end_dt,
        uid="..."
        organizer=organizer,
        description=".."
        status="CONFIRMED",
        location="..."
    )

    event.extra = Container("VEVENT", [ContentLine(name="SEQUENCE", value="0")])

```

But get error:

```
'list' object has no attribute 'clone'
```

Am I doing something wrong?

**Comment by N-Coder** [comment]
Please do not overwrite the `extra` field, but only clear/append it in-place. We should probably wrap this in a read-only property to prevent this kind of problem...

**Comment by 2rueSid** [comment]
Thanks for the quick response!

But as I saw in the docs:
https://icspy.readthedocs.io/en/stable/advanced.html
I can actually do this.

By the way, I want to cancel a previously created event, how I can add a `SEQUENCE` line to achieve this?

**Comment by N-Coder** [comment]
The docs are unfortunately not up-to-date. What you want is probably the following:
```python
event.extra.append(ContentLine(name="SEQUENCE", value="0"))
```

**Comment by 2rueSid** [comment]
Thanks a lot!
