### ISSUE TITLE
Linux and Windows produce different .ics files

### ISSUE THREAD

**Issue by sonejostudios** [ics-py/ics-py#424]
Hi Devs,

I'm developing an app for Linux and Windows, which uses ics-py. The idea is to subscribe this exported local .ics with thunderbird. 
For some reasons, the exported .ics file is different depending on the OS. I'm useing exactly the same python code on both OS.

* On Linux, everything looks fine, and thunderbird can subscribe the ics without any problems.
* On Windows, the ics has a lot of new lines in it (one after every line), thunderbird can subscribe it but can't parse the events. It is possible to import the file though, but it is not the idea since it should be fully automated. Also the event order is different (don't know if this is relevant, though)
 
Since it is working as expected on Linux, I assume there is a bug on Windows when generating th ics file.

I attached both versions here (I had to rename them to .txt to allow uploading them):
[LINUX.txt](https://github.com/user-attachments/files/17893906/LINUX.txt)
[WINDOWS.txt](https://github.com/user-attachments/files/17893907/WINDOWS.txt)

Thank you for the help!

**Comment by N-Coder** [comment]
The line endings are set by the RFC and generated correctly by this library (at least by the current alpha version), so this is probably an issue arising from some Windows line ending conversion happening somewhere in your pipeline. Does the import work with our example from the README?

**Comment by sonejostudios** [comment]
Hey @N-Coder , thank you for your reply!

by the way, I'm using ics 0.7.2 and python 3.10.

Unfortunately the code provided by the README.rst uses c.append(), which is not working. But the c.add() from the ducumentation works great. I also tried my_file.write(c.serialize()) instead of my_file.writelines(c.serialize_iter()) but this doesn't change anything.

As I wrote, I'm using EXACTLY the same python code on both OS:

`    c = Calendar()
    for i, row in df_shows.iterrows():
        e = Event()
        e.name = row["City"] + " - " + row["Venue"]
        e.begin = row["Date"]
        e.make_all_day()
        c.events.add(e)

    # export
    export_path = "my.ics"
    with open(export_path, 'w') as my_file:
        #my_file.writelines(c.serialize_iter())
        my_file.write(c.serialize())`

So what could it be? 
Should I update the RFC library?

**Comment by N-Coder** [comment]
> by the way, I'm using ics 0.7.2 and python 3.10.

Please try the current Master branch or the alpha version from PyPi and see if the problem persists. If it does, please create two example files and post them here _without_ editing with a text editor beforehand.

**Comment by sonejostudios** [comment]
I tried with ics.py 0.8.0.dev0, the problem persists.

The uploaded files are NOT edited by any text editor, I just renamed the file extension from .ics to .txt (because github won't allow me to upload .ics, but .txt).

**Comment by juengling** [comment]
In confirm the problem with ics v0.7.2, Python 3.12 (64bit) and Thunderbird 128.5.1 on Windows 11.

The unedited file contains `CR` *and* `CRLF` control sequences (screeshot from Notepad++):

![demo-ics-file](https://github.com/user-attachments/assets/12520360-268c-4ae2-a6ed-dc6360e04c8c)

If I remove the extra `CR` in the .ics file with a file editor, Thunderbird can import the file.

**Comment by N-Coder** [comment]
Ah, this is an issue with [universal newlines](https://docs.python.org/3/library/functions.html#open) mode on Windows, where all `\n` are replaced with `\r\n` even if they were already preceded by a `\r`. So the `repr` of the strings generated by ics.py will be the same on all platforms, you just have to tell python to really write this unchanged to disk independently of the platform:
```python
with open("my.ics", "w", newline="") as my_file:
```
I'll update the example in the readme once I get around to it...
