### ISSUE TITLE
Package for Ubuntu and Debian

### ISSUE THREAD

**Issue by PanderMusubi** [ics-py/ics-py#96]
Please vote or help with https://bugs.launchpad.net/ubuntu/+bug/1633856 to get this packaged for Ubuntu and Debian.

**Comment by spaceone** [comment]
This would be nice.

**Comment by C4ptainCrunch** [comment]
Having enough time to support the PyPi package is hard enough, maintaining a .deb will be way too much i think. 
Plus : ics.py is still in beta, i'm guessing it is too young to be packaged in a distro so i'm closing this :)
